language: go
go:
- 1.9
git:
  depth: false
script: make; go test ./...; sudo scripts/run_tests.sh
before_deploy:
- mkdir build
- cp tosi build/tosi
deploy:
  provider: s3
  access_key_id: AKIA2BCIPONCYWNSPTDL
  secret_access_key:
    secure: k3GjDIcIkfe7vNskQi+BF+0V32o+BDb24z9Z5vzZaTBq9NLHouZadXFwzzCKYIkLA5TiULVE7frSvUVyL8O9vhimMwoPW8zbILLHDbfisGwnU4wWw5SxN+nuGOAlb6dYf0V4CtdHuwNoFbsDezGTHiFJ6aXnwden9ZlsTxqcKPEE+YwOoBRMEAn9Ya6X8+DIIXetjlRM1bUl0Cfy0l09P2d6JV1NIKkIM9fiMkwq0w1vOe50i3F04VHAXUMCDlVIn/oeovyGSMUjmBfj8mewFLatTYE5546lywZTOFknopZg5y8sVoDmqjoOum4g0irsOwOHsv3ZhkJjzvWQF54QHCHkHMkpvA08i34RnIaCoTFWM7myBPyAJRyUSVWrHlc0Lza/DPATUTWOrX5jJ226VCS7jYNrOo1nlpaFkae1/wYMg7Y5yqAgTTnsVlJXf5Y3DQpQwTHGW7UK7Laq13sdNxUNQWxvL8o5gUtbXYPkWYt9/ChTpwICs+4uNAndue467EHkewdQAab3IxgI1gx7mriujhtCUNNpb/DrIA7j3mewwjF8FmYTyYkFcDGNEe6OzFOHY5AyIQdjEl7+nqNiid7v6jRIAmXv0rQTRnk3o7MNIFbP9W1TOEWoNrF0h6BB0uHTErTzTEmEnqXsqJ473tWoFaTwIZPkZay7BncTrNE=
  bucket: tosi
  acl: public_read
  on:
    repo: elotl/tosi
  skip_cleanup: true
  local_dir: build
