language: go
go:
- 1.9
git:
  depth: false
script: make; go test ./...; sudo scripts/run_tests.sh
before_deploy:
- mkdir build
- cp tosi build/tosi
deploy:
  provider: s3
  access_key_id: AKIA2BCIPONC34DS3XPR
  secret_access_key:
    secure: Ifhl/4RMwSJjL6ZnZ6DCFNdhZXjrpdqKgxCeT3NbjMKj5UVCanoeZzrvPaYFrYKUIrQePbS6c4wJLvrJT0nx9Q8U1D0w/iZT0Gf0eIqDvGSCUJXsqkk+u9ZaprXELAafUACh75Bd/5p6rgr9rAfcrJje7qb8AzGe6S65nMSw1ZVaYkFUyGfeEbvO87qaxOGN/8pWIoVajrDbFTSeaQAyFmCWEU7ZfBXLQmyTaTvKP0IU+KUDniMlBbcw6T39gaUabKkZsocaQ0UgM441hED+Dz8U42+CRfscVqXCKQtuNRKC9st6zo13vFTNS4SFGgkHAFcok156U3gEQsgErmOI3JKWtZB6d2cPt/EySRMFAi5GYcWW4PaClfBEZu9VEN70k/bCLXHCnB+SuEIDq63AOqjuMTNsACnhR52RKgSu9HFBZBQYxjvw5y9yTKkFpxZWM5oioSzfQFencAkNpPR/JKU41v34XNW0Hwdak4a/cxreKpL4ta4osrjGLt0i+Vol8NJPxELlVVKI+rMcDWnNXR+GLJ6eve2nDMwENLgOOEn+EsCOnihNueDZX763BlSgDxkfnRC1dJPnq8iw4XC3If+/OYIkxk5fPApYB/fJVSqTkampLs8YsdXVV+VhtCXSbBzzzViCytSDqEzIkgW4j2tai49De+Xek6dLGPgxpJQ=
  bucket: tosi
  acl: public_read
  on:
    repo: elotl/tosi
  skip_cleanup: true
  local_dir: build
