language: go
go:
- 1.9
git:
  depth: false
script: make; go test ./...; sudo scripts/run_tests.sh
before_deploy:
- mkdir build
- cp tosi build/tosi
deploy:
  provider: s3
  access_key_id: AKIA2BCIPONCZZBWXJNR
  secret_access_key:
    secure: RnGfv8D1UHoVp1JPTnZQEG2W4kiJ17/yp9jKy8EfZ7bgoDRw4dIrv7lIm+AeNysr3jKeppW5aWaj4ePw1plfnuFXFh4leSfF6jite3zS3I4IQz6yv1m9ZvTstL+jjVlMJaG7H6enlW1GtA0lJSxNpVSlW6YeAr0lLB1OLMftVF+5DXXKZDGmGjmYZ/DkaRWC6zCO3VIDkgpr4e696E8fFdyMNo2ScazfB67mcuYVweZWo81Za3ezPPkdLFiykk8Xe787rRaguM2JaeaDjHw2LP9yZYq6AyKratgnNFwm4t6JNoryLkQxBo5wujBiE9A0EC8zZfBGvLXHbgYFOHl58VTigqsVusDpRbtKSP+Pj3bxOCxjEnN/6HoaZxtmEkGKORTF2BRUdl0VOiC+RS8MB1ionWa9q97Z16IVXOrfc9aHYvfMKkQu6lkC6Aov5UQ02WLp8tVQaJKISoW41NPi1lsVX21j30vWA08MQlzWsOGbckU4qQ9cFvlT6LUowQ7P6V61NYPgNcKV9G4gKCMz4jTpoW+q1SLArTgQHu9L531MEwMbQRj0ODmybFPNGKi1wGCd/EwglM4cLy+WsAeNXwQhvxbBwI6mo9pPmUVlzS/KqT3HQwT+643SvyzkYFAsNfAzi+zI7iWeT/FoAqKQHpMLeosCNPWQc3Hxp8GTIGQ=
  bucket: tosi
  acl: public_read
  on:
    repo: elotl/tosi
  skip_cleanup: true
  local_dir: build
